stages:
  - deploy
  - test

deploy_job:
  stage: deploy
  when: always
  image: davidgortega/cml:cml-runner
  script:
    - cml-runner
      --cloud aws
      --cloud-region us-west
      --cloud-type g2.2xlarge
      --cloud-gpu tesla
      --cloud-spot
      --labels=cml-runner-gpu-gl

test_runner:
  when: on_success
  tags:
    - cml-runner-gpu-gl
  script:
    - sudo update-alternatives --install /usr/bin/python python $(which python3) 10
    - sudo apt-get update && sudo apt-get install -y python-pip python3-pip 
    - sudo pip install --upgrade pip
    - sudo pip install --upgrade setuptools
    - sudo pip install tensorboard

    - npm ci
    - npm run lint
    - npm run test 

    - nvidia-smi

test_container:
  image: dvcorg/cml-py3:latest
  when: on_success
  tags:
    - cml-runner-gpu-gl
  script:
    - dvc --version
    - pip install tensorboard

    - npm ci
    - npm run lint
    - npm run test

    - nvidia-smi