stages:
  - build
  - deploy
  - test

build_job:
  stage: build
  when: always
  script:
    - sudo add-apt-repository universe -y
    - sudo add-apt-repository ppa:git-core/ppa -y
    - sudo apt update && sudo apt-get install -y git
    - sudo curl -fsSL https://get.docker.com -o get-docker.sh && sudo sh get-docker.sh && \
    - sudo usermod -aG docker ubuntu
    - sudo setfacl --modify user:ubuntu:rw /var/run/docker.sock
    - docker build -t dvcorg/cml-test-gl -f ./docker/Dockerfile .

deploy_job:
  stage: deploy
  when: on_success
  image: dvcorg/cml-test-gl
  script:
    - cml-runner
      --cloud aws
      --cloud-region us-west
      --cloud-type g2.2xlarge
      --cloud-spot
      --labels=cml-runner-gpu

test_runner:
  stage: test
  when: on_success
  tags:
    - cml-runner-gpu
  script:
    - sudo update-alternatives --install /usr/bin/python python $(which python3) 10
    - sudo apt-get update && sudo apt-get install -y python-pip python3-pip 
    - sudo pip install --upgrade pip
    - sudo pip install --upgrade setuptools
    - sudo pip install tensorboard

    - npm ci
    - npm run lint
    - npm run test 

    - nvidia-smi

test_container:
  stage: test
  when: on_success
  tags:
    - cml-runner-gpu
  image: dvcorg/cml-py3:latest
  script:
    - dvc --version
    - pip install tensorboard

    - npm ci
    - npm run lint
    - npm run test

    - nvidia-smi
  