default:
  before_script:
    - apt-get update

run:
  script:
    - npm ci
    - npm run lint

    - sudo apt-get update && sudo apt-get install -y python3-pip
    - sudo update-alternatives --install /usr/bin/python python $(which python3) 10
    - sudo pip install --upgrade pip
    - sudo pip install --upgrade setuptools
    - sudo pip install tensorboard
    - npm run test

