stages:
  - deploy
  - test

deploy_job:
  stage: deploy
  script:
    - apt-get update && apt-get install -y software-properties-common
    - curl -sL https://deb.nodesource.com/setup_12.x | bash
    - curl -fsSL https://apt.releases.hashicorp.com/gpg | apt-key add -
    - apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
    - apt update && apt-get install -y nodejs terraform

    - npm ci
    - npm link
    - cml-runner
      --cloud aws
      --cloud-region us-west
      --cloud-type=t2.micro
      --cloud-spot
      --labels=cml-runner
  when: always

test_runner:
  when: on_success
  tags:
    - cml-runner

  script:
    - sudo update-alternatives --install /usr/bin/python python $(which python3) 10
    - sudo apt-get update && sudo apt-get install -y python-pip python3-pip 
    - sudo pip install --upgrade pip
    - sudo pip install --upgrade setuptools
    - sudo pip install tensorboard

    - npm ci
    - npm run lint
    - npm run test 

test_container:
  when: on_success
  tags:
    - cml-runner

  image: dvcorg/cml-py3:latest
  script:
    - dvc --version
    - pip install tensorboard

    - npm ci
    - npm run lint
    - npm run test
