deploy-runner:
  image: iterativeai/cml:0-dvc2-base1
  script:
    - |
      cml runner \
          --cloud=aws \
          --cloud-region=us-west \
          --cloud-type=g4dn.xlarge \
          --cloud-spot \
          --labels=cml-runner-gpu
test-runner:
  needs: [deploy-runner]
  tags:
    - cml-runner-gpu
  script:
    - pip install tensorboard

    - npm ci
    - npm run lint
    - npm run test

    - nvidia-smi
test-container:
  needs: [deploy-runner]
  tags:
    - cml-runner-gpu
  image: iterativeai/cml:0-dvc2-base1-gpu
  script:
    - dvc --version
    - cml --version
    - pip install tensorboard

    - npm ci
    - npm run lint
    - npm run test

    - nvidia-smi
