name: check-container

on: [push]

jobs:
  build-container:
    runs-on: [ubuntu-18.04]

    steps:
      - name: Build test image and publish
        run: | 
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
          docker build -t dvcorg/cml-test -f ./docker/Dockerfile .
          docker publish dvcorg/cml-test

  check-actions:
    needs: build-container
    runs-on: [ubuntu-18.04]
    container: docker://dvcorg/cml-test

    steps:
      - uses: r-lib/actions/setup-r@master

      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
