name: "Update dependencies"

on: [push]
  # schedule:
  #   - cron: 0 0 * * *
 
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
  
jobs:
  test_and_deploy:
    runs-on: [ubuntu-latest]
    
    steps:
    - name: "Check dependencies"
      run: |
        sudo wget https://dvc.org/deb/dvc.list -O /etc/apt/sources.list.d/dvc.list
        sudo apt update && sudo apt -y install dvc
        CML_VER=$(docker run davidgortega/cml:latest dvc --version)
        DVC_VER=$(dvc --version)

        #echo "::set-output name=update::$([ $CML_VER == $DVC_VER ])"
        #echo "::set-output name=comment::Updating DVC from $(CML_VER) to $(DVC_VER)"
        echo "::set-output name=action_fruit::strawberry"

    - name: depe
      run: |
        printenv

    # - name: Create Pull Request
    #   uses: peter-evans/create-pull-request@v2
    #   with:
    #     title: 'chore: dependancron update dependencies'
    #     body: ''

    