name: "Update dependencies"

on: [push]
  # schedule:
  #   - cron: 0 0 * * *
 
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
  
jobs:
  test_and_deploy:
    runs-on: [ubuntu-latest]
    
    steps:
    - name: "Check dependencies"
      id: check
      run: |
        sudo wget https://dvc.org/deb/dvc.list -O /etc/apt/sources.list.d/dvc.list
        sudo apt update && sudo apt -y install dvc
        CML_VER=$(docker run davidgortega/cml:latest dvc --version)
        DVC_VER=$(dvc --version)
        UPDATE=false
        if [ "${CML_VER}" == "${$DVC_VER}" ]; then
          UPDATE=true
        fi

        echo "::set-output name=update::${UPDATE}"
        #echo "::set-output name=comment::Updating DVC from $(CML_VER) to $(DVC_VER)"

    - name: depe
      run: |
        echo ${{ steps.check.outputs.update }}

    # - name: Create Pull Request
    #   uses: peter-evans/create-pull-request@v2
    #   with:
    #     title: 'chore: dependancron update dependencies'
    #     body: ''

    