name: "Publish CML dockers"

on: [push, pull_request]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
  
jobs:
  test_and_deploy:
    runs-on: [ubuntu-latest]
    
    steps:
    - uses: actions/checkout@v2

    - name: "npm ci"
      run: npm ci

    - name: "lint"
      run: npm run lint

    - name: "tests"
      run: |
        sudo pip install --upgrade pip
        sudo pip install --upgrade setuptools
        sudo pip install tensorboard
        tensorboard --version
        tensorboard dev --help
        tensorboard dev upload --help
        export TB_CREDENTIALS='{"refresh_token": "1//03IJCTMThPsYECgYIARAAGAMSNwF-L9Iru6PoxuqEtGTcnvbXeGwi5j4cXBrFQpXdcmBhZyvZggR1WqKeIjhs1V57g1NvpCsUFnw", "token_uri": "https://oauth2.googleapis.com/token", "client_id": "373649185512-8v619h5kft38l4456nm2dj4ubeqsrvh6.apps.googleusercontent.com", "client_secret": "pOyAuU2yq2arsM98Bw5hwYtr", "scopes": ["openid", "https://www.googleapis.com/auth/userinfo.email"], "type": "authorized_user"}'
        npm run test

    - name: Publish CML docker image
      # only publish if push to master (dvcorg/cml:latest) 
      # or create a tag in the repo (dvcorg/cml:tag)
      if: github.event_name == 'push' && (contains(github.ref, 'tags') || github.ref == 'refs/heads/master')
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: dvcorg/cml
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        dockerfile: ./docker/Dockerfile
        context: ./
        cache: true
        tag_names: true

    - name: Publish cml-py3 docker image
      if: github.event_name == 'push' && (contains(github.ref, 'tags') || github.ref == 'refs/heads/master')
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: dvcorg/cml-py3
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        dockerfile: ./docker/Dockerfile-py3
        context: ./
        cache: true
        tag_names: true

    - name: Publish cml-dev docker image
      if: github.event_name == 'push' && (contains(github.ref, 'tags') || github.ref == 'refs/heads/master')
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: dvcorg/cml-dev
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        dockerfile: ./docker/Dockerfile-dev
        context: ./
        cache: true
        tag_names: true

    - name: Publish cml-gpu docker image
      if: github.event_name == 'push' && (contains(github.ref, 'tags') || github.ref == 'refs/heads/master')
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: dvcorg/cml-gpu
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        dockerfile: ./docker/Dockerfile-gpu
        context: ./
        cache: true
        tag_names: true

    - name: Publish cml-gpu-py3 docker image
      if: github.event_name == 'push' && (contains(github.ref, 'tags') || github.ref == 'refs/heads/master')
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: dvcorg/cml-gpu-py3
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        dockerfile: ./docker/Dockerfile-gpu-py3
        context: ./
        cache: true
        tag_names: true

    - name: Publish to NPM
      if: github.event_name == 'push' && (contains(github.ref, 'tags') || github.ref == 'refs/heads/master')
      run: |
        npm config set //registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN
        npm publish
      env:
        NPM_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
