name: Release packages and images
on:
  workflow_dispatch:
  release:
    types: [published]
jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          registry-url: https://registry.npmjs.org
      - run: npm install
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  docker:
    strategy:
      matrix:
        cml: [0]
        dvc: [1, 2]
        gpu: [false, true]
        base: [0, 1]
        include:
          - base: 0
            cuda: 10.1
            cudnn: 7
            python: 2.7
            ubuntu: 18.04
          - base: 1
            cuda: 11.0.3
            cudnn: 8
            python: 3.8
            ubuntu: 20.04
    runs-on: ubuntu-latest
    needs: package
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}
      - uses: docker/build-push-action@v2
        if: matrix.gpu == false
        with:
          push: true
          context: ./
          file: ./Dockerfile
          tags: |
            docker.io/dvcorg/cml:${{ matrix.cml }}-dvc${{ matrix.dvc }}-base${{
            matrix.base }}
            ghcr.io/iterative/cml:${{ matrix.cml }}-dvc${{ matrix.dvc }}-base${{
            matrix.base }}
          build-args: |
            CML_VERSION=${{ matrix.cml }}
            DVC_VERSION=${{ matrix.dvc }}
            PYTHON_VERSION=${{ matrix.python }}
            BASE_IMAGE=ubuntu:${{ matrix.ubuntu }}
      - uses: docker/build-push-action@v2
        if: matrix.gpu == true
        with:
          push: true
          context: ./
          file: ./Dockerfile
          tags: |
            docker.io/dvcorg/cml:${{ matrix.cml }}-dvc${{ matrix.dvc }}-base${{
            matrix.base }}-gpu
            ghcr.io/iterative/cml:${{ matrix.cml }}-dvc${{ matrix.dvc }}-base${{
            matrix.base }}-gpu
          build-args: |
            CML_VERSION=${{ matrix.cml }}
            DVC_VERSION=${{ matrix.dvc }}
            PYTHON_VERSION=${{ matrix.python }}
            BASE_IMAGE=nvidia/cuda:${{ matrix.cuda }}-cudnn${{ matrix.cudnn }}-runtime-ubuntu${{ matrix.ubuntu }}
