name: Test & Deploy
on:
  schedule:
    - cron: '0 9 * * 1' # M H d m w (Mondays at 9:00)
  release:
    types: [published]
  pull_request_target:
  workflow_dispatch:
jobs:
  authorize:
    environment:
      ${{ (github.event_name == 'pull_request_target' &&
      github.event.pull_request.head.repo.full_name != github.repository) &&
      'external' || 'internal' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo ✓
  lint:
    needs: authorize
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha || github.ref }}
      - uses: actions/setup-node@v2
      - run: npm ci
      - run: npm run lint
  test:
    needs: authorize
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha || github.ref }}
      - uses: actions/setup-node@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - run: pip install tensorboard
      - run: npm ci
      - run: npm run test
        env:
          GITHUB_TOKEN: ${{ github.token }}
          TEST_GITHUB_TOKEN: ${{ secrets.TEST_GITHUB_TOKEN }}
          TEST_GITHUB_REPO: https://github.com/iterative/cml_qa_tests_dummy
          TEST_GITHUB_SHA: 0cd16da26e35f8e5d57b2549a97e22618abf08f6
          TEST_GITLAB_TOKEN: ${{ secrets.TEST_GITLAB_TOKEN }}
          TEST_GITLAB_REPO: https://gitlab.com/iterative.ai/cml_qa_tests_dummy
          TEST_GITLAB_SHA: f8b8b49a253243830ef59a7f090eb887157b2b67
          TEST_BBCLOUD_TOKEN: ${{ secrets.TEST_BBCLOUD_TOKEN }}
          TEST_BBCLOUD_REPO: https://bitbucket.org/iterative-ai/cml-qa-tests-dummy
          TEST_BBCLOUD_SHA: b511535a89f76d3d311b1c15e3e712b15c0b94e3
  test-os:
    needs: authorize
    name: test-${{ matrix.system }}
    strategy:
      matrix:
        system: [ubuntu, macos, windows]
    runs-on: ${{ matrix.system }}-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha || github.ref }}
      - if: matrix.system == 'windows'
        uses: actions/setup-node@v2
      - run: |
          npm i -g
          cml --version
          cml runner --version
          cml publish --version
          cml pr --version
      - if: matrix.system != 'windows'
        run: |
          cml-runner --version
          cml-publish --version
          cml-pr --version
      - if:
          matrix.system == 'ubuntu' pkg -t node14-linux,node14-macos
          package.json ./build/cml-linux publish assets/test.svg
      - if:
          matrix.system == 'macos' pkg -t node14-linux,node14-macos package.json
          ./build/cml-macos publish assets/test.svg

  packages:
    needs: [lint, test, test-os]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha || github.ref }}
      - uses: actions/setup-node@v2
        with:
          registry-url: https://registry.npmjs.org
      - run: npm install
      - run:
          npm ${{ github.event_name == 'release' && 'publish' || 'publish
          --dry-run' }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  binaries:
    needs: authorize
    name: binaries-${{ matrix.system }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha || github.ref }}

      - name: build
        run: |
          pkg -t node14-linux,node14-macos package.json

      - uses: JasonEtco/upload-to-release@master
        with:
          args: build/cml-macos application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: JasonEtco/upload-to-release@master
        with:
          args: build/cml-linux application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  images:
    runs-on: ubuntu-latest
    needs: packages
    strategy:
      matrix:
        dvc: [1, 2]
        base: [0, 1]
        gpu: [false, true]
        include:
          - base: 0
            ubuntu: 18.04
            python: 2.7
            cuda: 10.1
            cudnn: 7
          - base: 1
            ubuntu: 20.04
            python: 3.8
            cuda: 11.0.3
            cudnn: 8
          - latest: true # update the values below after introducing a new major version
            base: 1
            dvc: 2
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha || github.ref }}
          fetch-depth: 0
      - name: Metadata
        id: metadata
        run: |
          latest_tag=$(git describe --tags | cut -d- -f1)
          cml_version=${latest_tag##v}
          dvc_version=$(python3 -c '
          from distutils.version import StrictVersion as Ver
          from urllib.request import urlopen
          from json import load
          data = load(urlopen("https://pypi.org/pypi/dvc/json"))
          ver_pre = "${{ matrix.dvc }}".rstrip(".") + "."
          print(
              max(
                  (i.strip() for i in data["releases"] if i.startswith(ver_pre)),
                  default="${{ matrix.dvc }}",
                  key=Ver
              )
          )')
          echo ::set-output name=cache_tag::${cml_version}-${dvc_version}-${{ matrix.base }}-${{ matrix.gpu }}
          echo ::set-output name=cml_version::$cml_version
          tag=${cml_version//.*/}-dvc${{ matrix.dvc }}-base${{ matrix.base }}
          if [[ ${{ matrix.gpu }} == true ]]; then
            echo ::set-output name=base::nvidia/cuda:${{ matrix.cuda }}-cudnn${{ matrix.cudnn }}-runtime-ubuntu${{ matrix.ubuntu }}
            tag=${tag}-gpu
          else
            echo ::set-output name=base::ubuntu:${{ matrix.ubuntu }}
          fi

          TAGS="$(
            for registry in docker.io/{dvcorg,iterativeai} ghcr.io/iterative; do
              if [[ "${{ matrix.latest }}" == "true" ]]; then
                if [[ "${{ matrix.gpu }}" == "true" ]]; then
                  echo "${registry}/cml:latest-gpu"
                else
                  echo "${registry}/cml:latest"
                fi
              fi
              echo "${registry}/cml:${tag}"
            done | head -c-1
          )"
          echo ::set-output name=tags::"${TAGS//$'\n'/'%0A'}"
      - uses: docker/setup-buildx-action@v1
      - uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key:
            ${{ runner.os }}-buildx-${{ steps.metadata.outputs.cache_tag }}-${{
            github.sha }}
          restore-keys:
            ${{ runner.os }}-buildx-${{ steps.metadata.outputs.cache_tag }}-
      - uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}
      - uses: docker/build-push-action@v2
        with:
          push:
            ${{ github.event_name == 'release' || github.event_name ==
            'schedule' || github.event_name == 'workflow_dispatch' }}
          context: ./
          file: ./Dockerfile
          tags: |
            ${{ steps.metadata.outputs.tags }}
          build-args: |
            CML_VERSION=${{ steps.metadata.outputs.cml_version }}
            DVC_VERSION=${{ matrix.dvc }}
            PYTHON_VERSION=${{ matrix.python }}
            BASE_IMAGE=${{ steps.metadata.outputs.base }}
          pull: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
      - name: Move cache
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
